### PR TITLE
Add hostname option

### PR DESCRIPTION
**Pull request by silsha**
I've added an option to set a hostname.

### CODE REVIEW

**Comment by dkumor** [comment]
Thanks! I'll verify it once I get home in a few hours, and get an update published to the chrome store.

**Comment by silsha** [comment]
There seems to be a cors issue when developer mode is deactivated. I'm not sure yet if that's a problem with my server or with the plugin.

**Comment by silsha** [comment]
Nevermind, was a problem with my server configuration.

**Comment by dkumor** [comment]
Cors is also an option in connectordb.conf - and I think that in 0.3.0a1 has a bug when cors is off (which will be fixed in the first beta coming out soon)

**Pull request merged**
